"""initial schema

Revision ID: 09446c2b8c7b
Revises: 
Create Date: 2026-08-12 12:15:48.201459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09446c2b8c7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('accent_color', sa.String(length=7), nullable=False),
    sa.Column('dark_color', sa.String(length=7), nullable=False),
    sa.Column('light_color', sa.String(length=7), nullable=False),
    sa.Column('sidebar_bg', sa.String(length=7), nullable=False),
    sa.Column('sidebar_text', sa.String(length=7), nullable=False),
    sa.Column('text_on_primary', sa.String(length=7), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('font_heading', sa.String(length=100), nullable=False),
    sa.Column('font_body', sa.String(length=100), nullable=False),
    sa.Column('border_radius', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('disponible', 'prestado', 'mantenimiento', 'baja', name='toolstatus'), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salvage_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('useful_life_years', sa.Integer(), nullable=False),
    sa.Column('depreciation_method', sa.Enum('lineal', 'uop', 'doble_saldo', name='depreciationmethod'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('jefe', 'encargado', 'mecanico', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=False),
    sa.Column('loan_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('activo', 'devuelto', 'vencido', 'extraviado', name='loanstatus'), nullable=False),
    sa.Column('return_condition', sa.Enum('bueno', 'dañado', 'reparacion', 'perdido', name='returncondition'), nullable=True),
    sa.Column('purpose', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('voucher_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_table('tools')
    op.drop_table('brand_configs')
    # ### end Alembic commands ###

    # Los ENUM de PostgreSQL no se eliminan automáticamente al borrar las
    # tablas que los usan — hay que dropearlos explícitamente o el próximo
    # upgrade falla con "type ... already exists".
    bind = op.get_bind()
    sa.Enum(name='returncondition').drop(bind, checkfirst=True)
    sa.Enum(name='loanstatus').drop(bind, checkfirst=True)
    sa.Enum(name='userrole').drop(bind, checkfirst=True)
    sa.Enum(name='depreciationmethod').drop(bind, checkfirst=True)
    sa.Enum(name='toolstatus').drop(bind, checkfirst=True)
