"""proveedores: direccion, telefono, email, contacto

Revision ID: 1f0f2f342350
Revises: 340bcb5f549f
Create Date: 2026-08-13 15:50:16.115307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f0f2f342350'
down_revision: Union[str, None] = '340bcb5f549f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('providers', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('providers', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('providers', sa.Column('address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'address')
    op.drop_column('providers', 'email')
    op.drop_column('providers', 'phone')
    op.drop_column('providers', 'contact_name')
    # ### end Alembic commands ###
