"""mantenimiento: multiples documentos (imagen o pdf)

Revision ID: 340bcb5f549f
Revises: 3c1aa94da705
Create Date: 2026-08-13 15:43:22.258938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340bcb5f549f'
down_revision: Union[str, None] = '3c1aa94da705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('maintenance_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_record_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_record_id'], ['maintenance_records.id'], name='fk_maintenance_documents_record_id'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name='fk_maintenance_documents_uploaded_by_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # Antes de borrar la columna vieja, migramos lo que ya hubiera cargado
    # a la tabla nueva — si no, cualquier comprobante ya subido se pierde.
    # El mime_type se adivina por extensión (no tenemos el archivo real a
    # mano acá, solo la URL) — es una migración de datos, no crítica si
    # algún caso raro cae en el default "image/jpeg".
    op.execute("""
        INSERT INTO maintenance_documents (maintenance_record_id, file_url, mime_type, uploaded_at)
        SELECT id, document_url,
               CASE
                   WHEN document_url ILIKE '%.pdf' THEN 'application/pdf'
                   WHEN document_url ILIKE '%.png' THEN 'image/png'
                   WHEN document_url ILIKE '%.webp' THEN 'image/webp'
                   ELSE 'image/jpeg'
               END,
               COALESCE(updated_at, created_at, now())
        FROM maintenance_records
        WHERE document_url IS NOT NULL
    """)
    op.drop_column('maintenance_records', 'document_url')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_records', sa.Column('document_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_table('maintenance_documents')
    # ### end Alembic commands ###
