"""modulo de mantenimiento y baja de herramientas

Revision ID: 350e367fc848
Revises: 611b81041e1d
Create Date: 2026-08-12 19:53:21.517389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350e367fc848'
down_revision: Union[str, None] = '611b81041e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('en_proceso', 'resuelto', 'sin_solucion', name='maintenancestatus'), nullable=False),
    sa.Column('sent_date', sa.Date(), nullable=False),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tools', sa.Column('decommission_reason', sa.Text(), nullable=True))
    op.add_column('tools', sa.Column('decommission_authorized_by_id', sa.Integer(), nullable=True))
    op.add_column('tools', sa.Column('decommission_date', sa.Date(), nullable=True))
    # Nombre explícito — con None, el downgrade autogenerado no puede
    # encontrar la FK para borrarla (ver el mismo comentario en la
    # migración ff993e164489 de cajas).
    op.create_foreign_key(
        'fk_tools_decommission_authorized_by_id_users',
        'tools', 'users', ['decommission_authorized_by_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('fk_tools_decommission_authorized_by_id_users', 'tools', type_='foreignkey')
    op.drop_column('tools', 'decommission_date')
    op.drop_column('tools', 'decommission_authorized_by_id')
    op.drop_column('tools', 'decommission_reason')
    op.drop_table('maintenance_records')
    # Postgres no elimina el ENUM al borrar la tabla que lo usaba — hay que
    # dropearlo a mano o la próxima corrida de "upgrade" falla con
    # "type maintenancestatus already exists" (mismo patrón que la
    # migración inicial con toolstatus/userrole/etc).
    sa.Enum(name='maintenancestatus').drop(op.get_bind(), checkfirst=True)
