"""herramientas: codigo de producto, folio y documento de compra

Revision ID: 3aa54bc75b72
Revises: 1f0f2f342350
Create Date: 2026-08-13 17:42:14.540245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa54bc75b72'
down_revision: Union[str, None] = '1f0f2f342350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Todas columnas nuevas nullable — se agrupan en una sola migración
    # porque son 3 cambios chicos e independientes (sin relación entre
    # sí, sin FKs nuevas, sin enums) pedidos en la misma tanda de feedback.
    op.add_column('maintenance_documents', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('maintenance_documents', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('providers', sa.Column('rut', sa.String(length=20), nullable=True))
    op.add_column('tools', sa.Column('product_code', sa.String(length=100), nullable=True))
    op.add_column('tools', sa.Column('purchase_document_folio', sa.String(length=100), nullable=True))
    op.add_column('tools', sa.Column('purchase_document_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_tools_product_code'), 'tools', ['product_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tools_product_code'), table_name='tools')
    op.drop_column('tools', 'purchase_document_url')
    op.drop_column('tools', 'purchase_document_folio')
    op.drop_column('tools', 'product_code')
    op.drop_column('providers', 'rut')
    op.drop_column('maintenance_documents', 'note')
    op.drop_column('maintenance_documents', 'title')
    # ### end Alembic commands ###
