"""auditoria e inventario de cajas de herramientas

Revision ID: 3c1aa94da705
Revises: 350e367fc848
Create Date: 2026-08-12 20:13:03.924675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1aa94da705'
down_revision: Union[str, None] = '350e367fc848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolbox_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toolbox_id', sa.Integer(), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('en_progreso', 'completado', name='toolboxauditstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['toolbox_id'], ['toolboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toolbox_audit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('bueno', 'dañado', 'faltante', name='audititemcondition'), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('sent_to_maintenance', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['toolbox_audits.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('toolbox_audit_items')
    op.drop_table('toolbox_audits')
    # Postgres no borra los ENUM al borrar las tablas que los usan — hay que
    # dropearlos a mano o el próximo "upgrade" falla con "type ... already
    # exists" (mismo patrón que las demás migraciones de este proyecto).
    bind = op.get_bind()
    sa.Enum(name='audititemcondition').drop(bind, checkfirst=True)
    sa.Enum(name='toolboxauditstatus').drop(bind, checkfirst=True)
