"""tablas maestras: marca categoria ubicacion proveedor

Revision ID: 7bd02cee9ddd
Revises: ff993e164489
Create Date: 2026-08-12 19:13:41.811307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd02cee9ddd'
down_revision: Union[str, None] = 'ff993e164489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    # ### end Alembic commands ###

    # Sembramos las tablas maestras con los valores distintos que ya estén
    # cargados en tools.brand/category/location/supplier — si no hacemos
    # esto, el desplegable del formulario aparece vacío para instalaciones
    # que ya tenían herramientas cargadas antes de esta migración.
    bind = op.get_bind()
    bind.execute(sa.text(
        "INSERT INTO brands (name, created_at) "
        "SELECT DISTINCT brand, now() FROM tools WHERE brand IS NOT NULL AND brand <> '' "
        "ON CONFLICT (name) DO NOTHING"
    ))
    bind.execute(sa.text(
        "INSERT INTO categories (name, created_at) "
        "SELECT DISTINCT category, now() FROM tools WHERE category IS NOT NULL AND category <> '' "
        "ON CONFLICT (name) DO NOTHING"
    ))
    bind.execute(sa.text(
        "INSERT INTO locations (name, created_at) "
        "SELECT DISTINCT location, now() FROM tools WHERE location IS NOT NULL AND location <> '' "
        "ON CONFLICT (name) DO NOTHING"
    ))
    bind.execute(sa.text(
        "INSERT INTO providers (name, created_at) "
        "SELECT DISTINCT supplier, now() FROM tools WHERE supplier IS NOT NULL AND supplier <> '' "
        "ON CONFLICT (name) DO NOTHING"
    ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
