"""2fa totp para usuarios

Revision ID: c2b598057a80
Revises: a8859d8b2b22
Create Date: 2026-08-12 13:56:28.668574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b598057a80'
down_revision: Union[str, None] = 'a8859d8b2b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    # server_default es necesario para backfillear las filas existentes —
    # default=False en el modelo es solo del lado de Python/ORM, no alcanza
    # a una tabla que ya tiene datos (ALTER TABLE ... NOT NULL falla si no
    # hay valor para las filas viejas).
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('users', 'totp_enabled', server_default=None)  # el default para filas nuevas lo pone el ORM
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
